name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '8.10'
            cabal: '3.2'
          - ghc: '9.0'
            cabal: '3.4'
          - ghc: '9.2'
            cabal: '3.6'
          - ghc: '9.4'
            cabal: '3.8'
          - ghc: '9.6'
            cabal: '3.10'
          - ghc: '9.8'
            cabal: 'latest'
          - ghc: '9.10'
            cabal: 'latest'
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: |
          ~/.local/state/cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}

    - name: Install cabal/ghc
      run: |
        ghcup install ghc --set ${{ matrix.versions.ghc }}
        ghcup install cabal --set ${{ matrix.versions.cabal }}

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --enable-benchmarks --disable-optimization all
    - name: Build and test
      run: |
          cabal v2-build --enable-tests --enable-benchmarks --disable-optimization all
          cabal v2-test --disable-optimization all

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install stack
      shell: cmd
      run: |
          choco install haskell-stack
    - name: Install dependencies
      run: |
          stack update
          stack test --dependencies-only --fast
    - name: Build and test
      shell: cmd
      run: |
          stack test --fast

  macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install stack
      run: |
          curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz -o stack.tar.gz
          tar xzvf stack.tar.gz --strip-components=1 'stack*/stack'
    - name: Install dependencies
      run: |
          ./stack update
          ./stack test --dependencies-only --fast
    - name: Build and test
      run: |
          ./stack install --fast --test --haddock --no-haddock-deps
